version: "3.8"

services:
  nodejsdevelopment:
    image: nodejs-demo-image:latest
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - app-network

networks:
  app-network:
    name: app-network